# Modified from https://github.com/pmeier/light-the-torch
# Modified from https://github.com/pytorch/ignite/blob/master/.github/workflows/pytorch-version-tests.yml
name: build-coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  build-coverage:
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#           - windows-latest
#           - macos-latest
        python-version: [3.7, 3.8, 3.9]
        pytorch-version:
          [1.11.0, 1.10.0, 1.9.1]  
          # 1.5.1, 1.4.0 Model load error in robustbench.
          # 1.8.1, 1.7.1, 1.6.0 'padding==same' error in TIFGSM
        exclude:
          - pytorch-version: 1.4.0
            python-version: 3.9
          - pytorch-version: 1.5.1
            python-version: 3.9
          - pytorch-version: 1.6.0
            python-version: 3.9
          # disabling python 3.9 support with PyTorch 1.7.1 and 1.8.1, to stop repeated pytorch-version test fail.
          # https://github.com/pytorch/ignite/issues/2383
          - pytorch-version: 1.7.1
            python-version: 3.9
          - pytorch-version: 1.8.1
            python-version: 3.9

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ## Install with https://github.com/pmeier/light-the-torch
      # - name: Setup development environment
      #   uses: ./.github/actions/setup-dev-env
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Collect environment information
      #   run: python ./.github/scripts/collect_env.py

      # - name: Install PyTorch distributions
      #   run:
      #     ltt install --pytorch-channel=${{ matrix.pytorch-channel }} torch torchvision
      #     torchaudio

      # - name: Check if CPU only
      #   shell: python
      #   run: |
      #     import sys
      #     import torch
      #     cuda = torch.version.cuda
      #     print(f"cuda = {cuda}")
      #     hip = torch.version.hip
      #     print(f"hip = {hip}")
      #     sys.exit(cuda or hip)

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Install PyTorch distributions
        shell: bash -l {0} # Use miniconda
        run:
          conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly python=${{ matrix.python-version }} -c pytorch

      - name: Install dependencies
        shell: bash -l {0} # Use miniconda
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        shell: bash -l {0} # Use miniconda
        run: |
          pip install pytest pytest-cov
          pytest --cov . --cov-report=xml

      - name: Upload coverage reports to Codecov
        shell: bash -l {0} # Use miniconda
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}